## Importation et Nettoyage

```{r}
source("Algo_Final.R")
source("Clean_Data.R")
source("Imputation_function.R")
source("Utilities_functions.R")
source("stop_sensor.R")
pacman::p_load(tidyverse,telraamStats,randomForest,ranger)

```

```{r}
dataV2 <- read.csv("/Users/paulvallee/Desktop/Stage CREM/Code R/data/20230518_20240517_v2_sensors_extract.csv")
dataV2$uptime_quality <- ifelse(dataV2$uptime >=0.5 ,TRUE,FALSE)
dataV2 <- dataV2 %>% rename(segment_name = segment_fullname) %>%  filter(segment_name != "") %>%  mutate(segment_name = as.factor(as.character(gsub("[0-9-]+", "",segment_name))),uptime = as.numeric(uptime))
dataV2 <- stop_sensor(dataV2)
dataV2 <- quarterly_to_hourly(dataV2)
```

```{r}
sensor1 <- dataV2 %>% filter(segment_id == 9000005665,uptime_quality) 
sensor2<- dataV2 %>% filter(segment_id == 9000002156,uptime_quality)
sensor3 <- dataV2 %>% filter(segment_id == 9000001877,uptime_quality)
sensor4 <- dataV2 %>% filter(segment_id == 9000004019,uptime_quality)
sensor5<- dataV2 %>% filter(segment_id == 9000006207,uptime_quality)
sensor6 <- dataV2 %>% filter(segment_id == 9000006227,uptime_quality)
sensor7 <- dataV2 %>% filter(segment_id == 9000004042,uptime_quality)


sensors <- list(sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7)

```

## Création jeu de donnée de test 

# Recuperer la distribution historique des données manquantes 
```{r}
load("/Users/paulvallee/Desktop/Stage CREM/Code R/data/segments_2ans.RData")
data_04$segment_name <- "RueDesEcoles-14"
segments <- rbind(data_01,data_02,data_04,data_05,data_06,data_07,data_08,data_10,data_11,data_13,data_14,data_15,data_16,data_18)
segments <- stop_sensor(segments,successive_day =2) 
segments_analyse <- segments %>% mutate(car = ifelse(uptime_quality,car,NA)) %>%  filter(is.na(car))

# Calculer la proportion de données manquantes historiques
historical_na_proportion <- segments %>% 
  group_by(segment_name, hour) %>%
  summarise(prop_na = sum(is.na(car)) / n(), .groups = 'drop') %>%
  na.omit()

# Calculer la moyenne des proportions de données manquantes par heure et par jour de la semaine
average_na_proportion <- historical_na_proportion %>%
  group_by(hour) %>%
  summarise(mean_prop_NA = mean(prop_na), .groups = 'drop') 
average_na_proportion

data_imput_list <- Create_test_data_with_na_distribution(dataV2,average_na_proportion,seed=1234)

```


```{r}
#data_imput_list<- Create_test_data_suite(dataV2, prop_missing=0.20,seed=1234)
data_imput_list <- Create_test_data_with_na_distribution(dataV2,average_na_proportion,seed=1234)

data_imput <- data_imput_list$test 
sum(is.na(data_imput$vehicule))
date_imput <- data_imput$date[which(is.na(data_imput$vehicle))]
val_reel <- data_imput_list$temoin  %>% filter(date %in% date_imput) %>% select(date,vehicle,hour,weekday,segment_name,pedestrian_lft,pedestrian,pedestrian_rgt,bike,bike_lft,bike_rgt,car,car_rgt,car_lft,heavy,heavy_lft,heavy_rgt) %>% rename(vehicle_reel=vehicle,
                                                pedestrian_lft_reel  =  pedestrian_lft,
                                                  pedestrian_reel = pedestrian,
                                                   pedestrian_rgt_reel = pedestrian_rgt,
                                                   bike_reel=  bike,
                                                  bike_lft_reel =  bike_lft,
                                                 bike_rgt_reel =   bike_rgt,
                                                   car_reel = car,
                                                   car_rgt_reel = car_rgt,
                                                  car_lft_reel =   car_lft,
                                                  heavy_reel =  heavy,
                                                   heavy_lft_reel =  heavy_lft,
                                                   heavy_rgt_reel= heavy_rgt                                                                                                                                                                                             )
val_reel
```

## Création des metrics 
```{r}
Create_metrics <- function(data_prev, data_reel, col_pred, col_reel, method_name) {
  
  epsilon <- 1e-10
  # Joindre les données réelles et prédites
  metrics_results <- data_reel %>%
    left_join(data_prev, by = c("date", "segment_name")) %>%
    filter(imputed != "original") %>%
    mutate(abs_error = abs(.data[[col_reel]] - .data[[col_pred]]),
           weekday = weekdays(date),
           hour = as.character(hour(date)))  # Convertir hour en caractère
  
  # Calcul du MAE global
  MAE_glob <- mean(metrics_results$abs_error, na.rm = TRUE)
  
  # Calcul des métriques par segment
  metrics_results_segment <- metrics_results %>%
    group_by(segment_name) %>%
    summarise(
      NMAE = mean(abs_error, na.rm = TRUE) / (mean(.data[[col_reel]], na.rm = TRUE) + epsilon)
    ) %>%
    ungroup()
  
  metrics_results_segment <- bind_rows(metrics_results_segment, 
                                       data.frame(segment_name = "Moyenne", 
                                                  NMAE = mean(metrics_results_segment$NMAE, na.rm = TRUE)))
  
  metrics_results_segment <- metrics_results_segment %>% 
    rename(!!paste0("NMAE_", method_name) := NMAE)
  
  # Calcul des métriques par jour
  metrics_results_day <- metrics_results %>%
    group_by(weekday) %>%
    summarise(
      NMAE = mean(abs_error, na.rm = TRUE) / (mean(.data[[col_reel]], na.rm = TRUE) + epsilon)
    ) %>%
    ungroup()
  
  metrics_results_day <- bind_rows(metrics_results_day, 
                                   data.frame(weekday = "Moyenne", 
                                              NMAE = mean(metrics_results_day$NMAE, na.rm = TRUE)))
  
  metrics_results_day <- metrics_results_day %>% 
    rename(!!paste0("NMAE_", method_name) := NMAE)
  
  # Calcul des métriques par heure
  metrics_results_hour <- metrics_results %>%
    group_by(hour) %>%
    summarise(
      NMAE = mean(abs_error, na.rm = TRUE) / (mean(.data[[col_reel]], na.rm = TRUE) + epsilon)
    ) %>%
    ungroup()
  
  metrics_results_hour <- bind_rows(metrics_results_hour, 
                                    data.frame(hour = "Moyenne", 
                                               NMAE = mean(metrics_results_hour$NMAE, na.rm = TRUE))) %>% arrange(hour)
  
  metrics_results_hour <- metrics_results_hour %>% 
    rename(!!paste0("NMAE_", method_name) := NMAE)
  
  # Renommer le MAE global
  result_list <- list(metrics_results_segment, 
                      metrics_results_day, 
                      metrics_results_hour, 
                      MAE_glob)
  
  names(result_list) <- c("NMAE_sensors", 
                          "NMAE_days", 
                          "NMAE_hours", 
                          paste0("MAE_glob_", method_name))
  
  return(result_list)
}
```



# Algorithme MAE jour/heure 
```{r}
data_MA_pred <- impute_NA_vehicle(data_imput,window=7) %>% filter(imputed != "original")
res_MA <- Create_metrics(data_MA_pred, val_reel, "vehicle", "reel","MA")
res_MA 

```



# Algorithme Random Forest 


```{r}
data_imput_rf <- data_imput %>%  select(vehicle, day_of_month, hour, weekday, month, year, vacation, season, week_number, segment_name,date)
data_train <- data_imput_rf %>% filter(!is.na(vehicle)) %>% na.omit() %>% mutate( imputed = "original")
data_test <-  data_imput_rf %>% filter(is.na(vehicle)) %>% mutate( imputed = "imputed")


foret <- ranger(vehicle ~ . - date, data = data_train, mtry = 8, min.node.size = 1,importance = "impurity")

# Faire les prédictions
predictions <- predict(foret1, data = data_test)$predictions

data_test <- data_test %>%
  mutate(predicted_vehicle = predictions)

res_RF <- Create_metrics(data_test, val_reel, "predicted_vehicle", "vehicle_reel","RF")
res_RF

#Visualiser les résultats data_test_prediction vs val_reel

data_comp <- data_test %>% select(date,weekday,hour ,segment_name, predicted_vehicle) %>% left_join(val_reel %>% select(date, segment_name, reel), by = c("date", "segment_name"))
data_comp %>% ggplot(aes(x = reel, y = predicted_vehicle)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(title = "Comparaison des valeurs prédites et réelles",
       x = "Valeurs réelles",
       y = "Valeurs prédites")


```



```{r}
data_imput_seg <- data_imput %>% filter(segment_name == "  Rue Fabien Burel")
data_imput_rf <- data_imput_seg %>%  select(vehicle, day_of_month, hour, weekday, month, year, vacation, season, week_number, segment_name,date)
data_train <- data_imput_rf %>% filter(!is.na(vehicle)) %>% na.omit() %>% mutate( imputed = "original")
data_test <-  data_imput_rf %>% filter(is.na(vehicle)) %>% mutate( imputed = "imputed")


foret <- ranger(vehicle ~ . - date, data = data_train, mtry = 8, min.node.size = 1,importance = "impurity")

# Faire les prédictions
predictions <- predict(foret1, data = data_test)$predictions

data_test <- data_test %>%
  mutate(predicted_vehicle = predictions)

res_RF <- Create_metrics(data_test, val_reel, "predicted_vehicle", "vehicle_reel","RF")
res_RF

#Visualiser les résultats data_test_prediction vs val_reel

data_comp <- data_test %>% select(date,weekday,hour ,segment_name, predicted_vehicle) %>% left_join(val_reel %>% select(date, segment_name, reel), by = c("date", "segment_name"))
data_comp %>% ggplot(aes(x = reel, y = predicted_vehicle)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(title = "Comparaison des valeurs prédites et réelles",
       x = "Valeurs réelles",
       y = "Valeurs prédites")


```


```{r}


data_imput<- data_imput %>% mutate(car = ifelse(is.na(vehicle),NA,car))
data_imput_rf <- data_imput %>%  select(car, day_of_month, hour, weekday, month, year, vacation, season, week_number, segment_name,date)
data_train <- data_imput_rf %>% filter(!is.na(car)) %>% na.omit() %>% mutate( imputed = "original")
data_test <-  data_imput_rf %>% filter(is.na(car)) %>% mutate( imputed = "imputed")


foret <- ranger(car ~ . - date, data = data_train, mtry = 8, min.node.size = 1,importance = "impurity")

# Faire les prédictions
predictions <- predict(foret, data = data_test)$predictions

data_test <- data_test %>%
  mutate(predicted_car= predictions)

res_RF <- Create_metrics(data_test, val_reel, "predicted_car", "car_reel","RF")
res_RF

#Visualiser les résultats data_test_prediction vs val_reel

data_comp <- data_test %>% select(date,weekday,hour ,segment_name, predicted_car) %>% left_join(val_reel %>% select(date, segment_name, car_reel), by = c("date", "segment_name"))
data_comp %>% ggplot(aes(x = car_reel, y = predicted_car)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(title = "Comparaison des valeurs prédites et réelles",
       x = "Valeurs réelles",
       y = "Valeurs prédites")



```

```{r}
data_imput<- data_imput %>% mutate(heavy = ifelse(is.na(vehicle),NA,heavy))
data_imput_rf <- data_imput %>%  select(heavy, day_of_month, hour, weekday, month, year, vacation, season, week_number, segment_name,date)
data_train <- data_imput_rf %>% filter(!is.na(heavy)) %>% na.omit() %>% mutate( imputed = "original")
data_test <-  data_imput_rf %>% filter(is.na(heavy)) %>% mutate( imputed = "imputed")


foret <- ranger(heavy ~ . - date, data = data_train, mtry = 8, min.node.size = 1,importance = "impurity")

# Faire les prédictions
predictions <- predict(foret, data = data_test)$predictions

data_test <- data_test %>%
  mutate(predicted_heavy= predictions)

res_RF <- Create_metrics(data_test, val_reel, "predicted_heavy", "heavy_reel","RF")
res_RF
res_RF_heavy
#Visualiser les résultats data_test_prediction vs val_reel

data_comp <- data_test %>% select(date,weekday,hour ,segment_name, predicted_heavy) %>% left_join(val_reel %>% select(date, segment_name, heavy_reel), by = c("date", "segment_name"))
p1 <- data_comp %>% ggplot(aes(x = heavy_reel, y = predicted_heavy)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(title = "Comparaison des valeurs prédites et réelles heavy = vehicle - car",
       x = "Valeurs réelles",
       y = "Valeurs prédites")


```

```{r}
# Préparation des données pour la prédiction des cars
data_imput_rf_car <- data_imput %>% select(car, day_of_month, hour, weekday, month, year, vacation, season, week_number, segment_name, date)
data_train_car <- data_imput_rf_car %>% filter(!is.na(car)) %>% na.omit() %>% mutate(imputed = "original")
data_test_car <- data_imput_rf_car %>% filter(is.na(car)) %>% mutate(imputed = "imputed")

# Modèle Random Forest pour les cars
foret_car <- ranger(car ~ . - date, data = data_train_car, mtry = 8, min.node.size = 1, importance = "impurity")

# Prédictions pour les cars
predictions_car <- predict(foret_car, data = data_test_car)$predictions

# Ajout des prédictions de cars au jeu de données de test
data_test_car <- data_test_car %>%
  mutate(predicted_car = predictions_car)

# Préparation des données pour la prédiction des vehicles
data_imput_rf_vehicle <- data_imput %>% select(vehicle, day_of_month, hour, weekday, month, year, vacation, season, week_number, segment_name, date)
data_train_vehicle <- data_imput_rf_vehicle %>% filter(!is.na(vehicle)) %>% na.omit() %>% mutate(imputed = "original")
data_test_vehicle <- data_imput_rf_vehicle %>% filter(is.na(vehicle)) %>% mutate(imputed = "imputed")

# Modèle Random Forest pour les vehicles
foret_vehicle <- ranger(vehicle ~ . - date, data = data_train_vehicle, mtry = 8, min.node.size = 1, importance = "impurity")

# Prédictions pour les vehicles
predictions_vehicle <- predict(foret_vehicle, data = data_test_vehicle)$predictions

# Ajout des prédictions de vehicles au jeu de données de test
data_test_vehicle <- data_test_vehicle %>%
  mutate(predicted_vehicle = predictions_vehicle)

# Calcul des heavy comme différence entre vehicles et cars
data_test_combined <- data_test_vehicle %>%
  mutate(predicted_car = data_test_car$predicted_car) %>%
  mutate(predicted_heavy = predicted_vehicle - predicted_car)

# Évaluation des résultats
res_RF_heavy <- Create_metrics(data_test_combined, val_reel, "predicted_heavy", "heavy_reel", "RF")
res_RF_heavy


# Visualiser les résultats pour les heavy
data_comp_heavy <- data_test_combined %>%
  select(date, weekday, hour, segment_name, predicted_heavy) %>%
  left_join(val_reel %>% select(date, segment_name, heavy_reel), by = c("date", "segment_name"))

p2 <- ggplot(data_comp_heavy, aes(x = heavy_reel, y = predicted_heavy)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(title = "Comparaison des valeurs prédites et réelles pour les heavy",
       x = "Valeurs réelles",
       y = "Valeurs prédites")


```


```{r}
gridExtra::grid.arrange(p1, p2, nrow = 2)
```


```{r}
data_imput_rf <- data_imput %>%  select(bike, day_of_month, hour, weekday, month, year, vacation, season, week_number, segment_name,date)
data_train <- data_imput_rf %>% filter(!is.na(bike)) %>% na.omit() %>% mutate( imputed = "original")
data_test <-  data_imput_rf %>% filter(is.na(bike)) %>% mutate( imputed = "imputed")


foret <- ranger(bike ~ . - date, data = data_train, mtry = 8, min.node.size = 1,importance = "impurity")

# Faire les prédictions
predictions <- predict(foret1, data = data_test)$predictions

data_test <- data_test %>%
  mutate(predicted_bike= predictions)

res_RF <- Create_metrics(data_test, val_reel, "predicted_bike", "bike_reel","RF")
res_RF

#Visualiser les résultats data_test_prediction vs val_reel

data_comp <- data_test %>% select(date,weekday,hour ,segment_name, predicted_bike) %>% left_join(val_reel %>% select(date, segment_name, bike_reel), by = c("date", "segment_name"))
data_comp %>% ggplot(aes(x = bike_reel, y = predicted_bike)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(title = "Comparaison des valeurs prédites et réelles",
       x = "Valeurs réelles",
       y = "Valeurs prédites")


```



```{r}
# Extraire l'importance des variables
importance_values <- importance(foret1)

# Convertir en dataframe pour ggplot2
importance_df <- data.frame(
  Variable = names(importance_values),
  Importance = importance_values
)

# Créer le graphique
ggplot(importance_df, aes(x = reorder(Variable, Importance), y = Importance)) +
  geom_bar(stat = 'identity',fill="skyblue") +
  coord_flip() +
  labs(title = 'Importance des Variables dans le RandomForest', x = 'Variables', y = 'Importance') +
  theme_minimal()
```


```{r}
#Si vehicule est NA alors mettre un NA dans car et heavy 
data_imput <- data_imput %>% mutate(car = ifelse(is.na(vehicle),NA,car) ,
                                    heavy = ifelse(is.na(vehicle),NA,heavy)  , 
                                     car_lft = ifelse(is.na(vehicle),NA,car_lft)  ,
                                    car_rgt = ifelse(is.na(vehicle),NA,car_rgt) ,
                                    heavy_lft = ifelse(is.na(vehicle),NA,heavy_lft) ,
                                    heavy_rgt = ifelse(is.na(vehicle),NA,heavy_rgt),
                                    bike =ifelse(is.na(vehicle),NA,bike),
                                    bike_rgt =ifelse(is.na(vehicle),NA,bike_rgt),
                                    bike_lft =ifelse(is.na(vehicle),NA,bike_lft),
                                    pedestrian_rgt =ifelse(is.na(vehicle),NA,pedestrian_rgt),
                                    pedestrian =ifelse(is.na(vehicle),NA,pedestrian),
                                    pedestrian_lft = ifelse(is.na(vehicle),NA,pedestrian_lft))



data_imput_rf <- data_imput %>%  select(vehicle, day_of_month, hour, weekday, month, year, vacation, season, week_number, segment_name,date)
data_train <- data_imput_rf %>% filter(!is.na(vehicle)) %>% na.omit() %>% mutate( imputed = "original")
data_test <-  data_imput_rf %>% filter(is.na(vehicle)) %>% mutate( imputed = "imputed")


foret <- ranger(vehicle ~ . - date, data = data_train, mtry = 8, min.node.size = 1,importance = "impurity")

# Faire les prédictions
predictions <- predict(foret1, data = data_test)$predictions

data_test <- data_test %>%
  mutate(predicted_vehicle = predictions)

res_RF <- Create_metrics(data_test, val_reel, "predicted_vehicle", "reel","RF")
res_RF

#Visualiser les résultats data_test_prediction vs val_reel

data_comp <- data_test %>% select(date,weekday,hour ,segment_name, predicted_vehicle) %>% left_join(val_reel %>% select(date, segment_name, reel), by = c("date", "segment_name"))
data_comp %>% ggplot(aes(x = reel, y = predicted_vehicle)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(title = "Comparaison des valeurs prédites et réelles",
       x = "Valeurs réelles",
       y = "Valeurs prédites")


```







#FineTune Random Forest 
```{r}

#Je veux trouver les meilleurs hyperparametres pour mon modèle de random forest regarde l'impact du changement de mtry. et min.node.size sur le NMAE des segments
#Je vais utiliser la fonction Create_metrics pour calculer le NMAE des segments pour chaque combinaison de mtry et min.node.size
#Je vais ensuite visualiser les résultats pour trouver les meilleurs hyperparamètres

#Définir les valeurs de mtry et min.node.size à tester
mtry_values <- seq(1:10)
min_node_size_values <- seq(1:20)

# Initialiser un dataframe pour stocker les résultats
results <- data.frame(mtry = numeric(), min_node_size = numeric(), NMAE = numeric())

# Boucle sur les valeurs de mtry et min.node.size
for (mtry in mtry_values) {
  for (min_node_size in min_node_size_values) {
    # Entraîner le modèle
    foret1 <- ranger(vehicle ~ . , data = data_train %>% select(- date), mtry = mtry, min.node.size = min_node_size)
    
    # Prédire les valeurs manquantes
    data_test <- data_test %>%
      mutate(predicted_vehicle = predict(foret1, data = data_test)$predictions)
    
    # Calculer le NMAE des segments
    res <- Create_metrics(data_test, val_reel, "predicted_vehicle", "reel", "rf")
    
    # Ajouter les résultats au dataframe
    results <- rbind(results, data.frame(mtry = mtry, min_node_size = min_node_size, NMAE = res$NMAE_sensors[8, 2] %>% pull()))
  }
}

results %>% arrange(NMAE) %>% head()



```

```{r}
res_RF
res_MA
```

```{r}
dataV2_car <- dataV2 %>% mutate(car = ifelse(!uptime_quality,NA,car),
                                heavy = ifelse(!uptime_quality,NA,heavy))
sum(is.na(dataV2_car$car))
```



```{r}

res_imput <- impute_missing_data(data_imput,transport_type = "vehicle",threshold_uptime = 0.7)
table(res_imput$imputed)
res_imput %>% filter(imputed == "imputed") %>% arrange(segment_id,date)
```




